#!/bin/bash

loadkeys ru
setfont cyr-sun16
timedatectl set-ntp true

#######################################


(
  echo o;

  echo n;
  echo;
  echo;
  echo;
  echo +300M;

  #echo n;
  #echo;
  #echo;
  #echo;
  #echo +20G;

  echo n;
  echo;
  echo;
  echo;
  echo +2048M;

  echo n;
  echo p;
  echo;
  echo;
  echo a;
  echo 1;

  echo w;
) | fdisk /dev/sda

lsblk


#######################################



mkfs.ext2  /dev/sda1
mkfs.ext4  /dev/sda3
mkswap /dev/sda2
#mkfs.ext4  /dev/sda4



mount /dev/sda3 /mnt
mkdir /mnt/{boot,home}
mount /dev/sda1 /mnt/boot
swapon /dev/sda2
#mount /dev/sda4 /mnt/home

##########################################



echo "Server = http://mirror.yandex.ru/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist

pacstrap /mnt base base-devel linux linux-firmware nano dhcpcd netctl

genfstab -pU /mnt >> /mnt/etc/fstab

arch-chroot /mnt sh -c "$(curl -fsSL git.io/Arch_BIOS2)"
