#!/bin/bash

loadkeys ru
setfont cyr-sun16
timedatectl set-ntp true
#######################################

(
  echo o;

  echo n;
  echo;
  echo;
  echo;
  echo +300M;

  #echo n;
  #echo;
  #echo;
  #echo;
  #echo +20G;

  echo n;
  echo;
  echo;
  echo;
  echo +2048M;

  echo n;
  echo p;
  echo;
  echo;
  echo a;
  echo 1;

  echo w;
) | fdisk /dev/vda

lsblk


#######################################

mkfs.ext2  /dev/vda1
mkfs.ext4  /dev/vda3
mkswap /dev/vda2
#mkfs.ext4  /dev/sda4

mount /dev/vda3 /mnt
mkdir /mnt/{boot,home}
mount /dev/vda1 /mnt/boot
swapon /dev/vda2
#mount /dev/sda4 /mnt/home

##########################################



echo "Server = http://mirror.yandex.ru/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist

pacstrap /mnt base base-devel linux linux-headers linux-firmware nano dhcpcd netctl

genfstab -pU /mnt >> /mnt/etc/fstab

arch-chroot /mnt 

#sh -c "$(curl -fsSL git.io/Arch_BIOS2)"




########################################################################################################
########################################################################################################
########################################################################################################
########################################################################################################
########################################################################################################
########################################################################################################
########################################################################################################
########################################################################################################
########################################################################################################
########################################################################################################




#####!/bin/bash
read -p "Введите имя компьютера: " hostname
read -p "Введите имя пользователя: " username


echo $hostname > /etc/hostname
ln -svf /usr/share/zoneinfo/Asia/Yekaterinburg /etc/localtime


echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen 
locale-gen

echo 'LANG="ru_RU.UTF-8"' > /etc/locale.conf
echo 'KEYMAP=ru' >> /etc/vconsole.conf
echo 'FONT=cyr-sun16' >> /etc/vconsole.conf


################################################################3


mkinitcpio -p linux

pacman -Syy
pacman -S grub --noconfirm 
grub-install /dev/vda
grub-mkconfig -o /boot/grub/grub.cfg



pacman -S dialog wpa_supplicant --noconfirm 
useradd -m -g users -G wheel -s /bin/bash $username

echo 'Создаем root пароль'
passwd

echo 'Устанавливаем пароль пользователя'
passwd $username

echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers

echo '[multilib]' >> /etc/pacman.conf
echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
pacman -Syy

pacman -S xorg-server xorg-xinit xorg-apps mesa-libgl lib32-mesa-libgl xterm virtualbox-guest-utils xfce4 xfce4-goodies sddm sddm-kcm --noconfirm
systemctl enable sddm

pacman -S ttf-liberation ttf-dejavu cantarell-fonts --noconfirm 

exit

