#!/bin/bash



mkfs.ext2 /dev/vda1 -L boot
echo;
mkfs.ext4 /dev/vda2 -L crypt
echo;


echo '


ШИФРОВАНИЕ ДИСКА ++++++++++

Введи слово YES


'
cryptsetup -yv luksFormat /dev/vda2
cryptsetup luksOpen /dev/vda2 container


#blkid -s UUID /dev/sdb3 | grep -oP '(?<=UUID=").+?(?=")'

#lsblk -no UUID /dev/vda2 > disk
#echo GRUB_CMDLINE_LINUX="cryptdevice=UUID=$disk:cryptx" >> /boot/grub/…'
