#!/bin/bash

loadkeys ru
setfont cyr-sun16
timedatectl set-ntp true
#######################################

(
  echo o;

  echo n;
  echo;
  echo;
  echo;
  echo +300M;

  #echo n;
  #echo;
  #echo;
  #echo;
  #echo +20G;

  #echo n;
  #echo;
  #echo;
  #echo;
  #echo +2048M;

  echo n;
  echo p;
  echo;
  echo;
  echo;
  echo a;
  echo 1;

  echo w;
) | fdisk /dev/vda

lsblk
